# See create-apps.sh that should be executed by a tenant admin.
# And not on the cloud shell, which currently does not work.
# The values put out by that script need to go into this terraform as params/values...